routes/web.php
<?php

use App\Http\Controllers\ArticleController;
use App\Http\Controllers\IndexController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', [IndexController::class,'index'])->name('index');


Route::resource('produit',\App\Http\Controllers\ProduitController::class);

Route::get('/tendances', function () {
    return view('trending');
})->name('trending');

Route::get('/produit', function () {
    return view('product');
})->name('product');

Route::resource('articles',ArticleController::class);

Route::get('/logout', function(){
    Auth::logout();
    return Redirect::to('login');
});

app/Models/Article.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    use HasFactory;

    protected $fillable=[
        'photo',
        'designation',
        'description',
        'prix',
        'type',
        'fournisseur_id'
    ];

}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\Models\Article;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Illuminate\Validation\Rule;
use Intervention\Image\Facades\Image;

class ArticleController extends Controller
{

    public function __construct()
    {
        $this->middleware(['role:fournisseur']);

    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $articles = DB::table('articles')
            ->select('id', 'photo', 'designation', 'description', 'prix', 'type')
            ->where('fournisseur_id', '=', auth()->user()->id)->get()->toArray(); // On recupere uniquement les articles du fournisseur
        return view('fournisseur.articles.index', ['articles' => $articles]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('fournisseur.articles.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
//        dd($request);
        $typeArticle = ['Frites', 'Pizza', 'Burger', 'Steak']; // Ceci est un tableau statique mais sera dynamisé apres étude complète du projet avec le client
        $validated = $request->validate([
            'photo' => 'required|image|mimes:jpg,jpeg,png,gif,svg|max:2048',
            'designation' => 'required|min:3',
            'description' => 'required|min:5',
            'prix' => 'required|numeric|min:3',
            'type' => 'required', Rule::in($typeArticle),
        ]);

        $image = $request->file('photo');
        $input['file'] = time() . '.' . $image->getClientOriginalExtension();

        $destinationPath = public_path('/fournisseur/articles');

        $destinationPath = public_path(DIRECTORY_SEPARATOR . "fournisseur" . DIRECTORY_SEPARATOR . "articles");

        $imgFile = Image::make($image->getRealPath());

        $imgFile->resize(360, 226)->save($destinationPath . DIRECTORY_SEPARATOR . $input['file']);

        $image->move($destinationPath, $input['file']);

        $fullUrl = $destinationPath . DIRECTORY_SEPARATOR . $input['file'];

        DB::beginTransaction(); // On demarre une transaction manuellement
        try {
            $article = new Article([
                'photo' => $fullUrl,
                'designation' => $request->designation,
                'description' => $request->description,
                'prix' => (int)$request->prix,
                'type' => $request->type,
                'fournisseur_id' => auth()->user()->id
            ]);
            $article->save;
        } catch (\Exception $e) {
            DB::rollBack(); // On annule la transaction
            Storage::delete($fullUrl); // Suppression de l'image precedement sotcké
            return back()->withErrors("Echec de l'opération");
        }
        DB::commit(); // On commit les informations dans la base de donées
        return redirect()->back()->with('success', 'Opération effectué avec success');
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Models\Article $article
     * @return \Illuminate\Http\Response
     */
    public function show(Article $article)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Models\Article $article
     * @return \Illuminate\Http\Response
     */
    public function edit(Article $article)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\Article $article
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Article $article)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Models\Article $article
     * @return \Illuminate\Http\Response
     */
    public function destroy(Article $article)
    {
        try {
            $article->delete();//On supprimer l'article apres confirmation
            unlink(public_path($article->photo));//Puis on supprime l'image sotcker
            return back()->with('success', 'Operation reussi');
        } catch (\Exception $e) {
            return back()->withErrors("Echec de l'opération");
        }
    }
}

resources/views/fournisseur/articles/create.blade.php
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Responsive Admin Dashboard Template">
    <meta name="keywords" content="admin,dashboard">
    <meta name="author" content="stacks">

    <!-- Title -->
    <title>Dashboard</title>

    <!-- Styles -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;300;400;500;600;700;800&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Two+Tone|Material+Icons+Round|Material+Icons+Sharp" rel="stylesheet">
    <link href="/adminAssets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/adminAssets/plugins/perfectscroll/perfect-scrollbar.css" rel="stylesheet">
    <link href="/adminAssets/plugins/pace/pace.css" rel="stylesheet">


    <!-- Theme Styles -->
    <link href="/adminAssets/css/main.min.css" rel="stylesheet">
    <link href="/adminAssets/css/custom.css" rel="stylesheet">

    <link rel="icon" type="image/png" sizes="32x32" href="/adminAssets/images/neptune.png" />
    <link rel="icon" type="image/png" sizes="16x16" href="/adminAssets/images/neptune.png" />

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<div class="app align-content-stretch d-flex flex-wrap">
    <div class="app-sidebar">
        <div class="logo">
            <a href="#" class="logo-icon"><span class="logo-text">Food Market</span></a>
            <div class="sidebar-user-switcher user-activity-online">
                <a href="#">
                    <img src="">
                    <span class="user-info-text">
                            {{auth()->user()->name}}
                        </span>
                </a>
            </div>
        </div>
        <div class="app-menu">
            <ul class="accordion-menu">
                <li class="sidebar-title">
                    Food Market
                </li>
                <li class="active-page">
                    <a href="#" class="active"><i class="material-icons-two-tone">dashboard</i>Dashboard</a>
                </li>
                @role('administrator')
                <li>
                    <a href=""><i class="material-icons-two-tone">star</i>Restaurant<i class="material-icons has-sub-menu">keyboard_arrow_right</i></a>
                    <ul class="sub-menu">
                        <li>
                            <a href="#">Liste</a>
                        </li>
                        <li>
                            <a href="#">Creer</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href=""><i class="material-icons-two-tone">star</i>Utilisateurs<i class="material-icons has-sub-menu">keyboard_arrow_right</i></a>
                    <ul class="sub-menu">
                        <li>
                            <a href="#">Liste</a>
                        </li>
                        <li>
                            <a href="#">Creer</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href=""><i class="material-icons-two-tone">star</i>Fournisseurs<i class="material-icons has-sub-menu">keyboard_arrow_right</i></a>
                    <ul class="sub-menu">
                        <li>
                            <a href="#">Liste</a>
                        </li>
                        <li>
                            <a href="#">Creer</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href=""><i class="material-icons-two-tone">star</i>Commandes<i class="material-icons has-sub-menu">keyboard_arrow_right</i></a>
                    <ul class="sub-menu">
                        <li>
                            <a href="#">Toutes les commandes par fournisseurs</a>
                        </li>
                        <li>
                            <a href="#">Commande validés</a>
                        </li>
                    </ul>
                </li>
                @endrole
                @role('fournisseur')
                <li>
                    <a href=""><i class="material-icons-two-tone">star</i>Articles<i class="material-icons has-sub-menu">keyboard_arrow_right</i></a>
                    <ul class="sub-menu">
                        <li>
                            <a href="{{route('articles.index')}}">Liste</a>
                        </li>
                        <li>
                            <a href="{{route('articles.create')}}">Creer</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href=""><i class="material-icons-two-tone">star</i>Commandes<i class="material-icons has-sub-menu">keyboard_arrow_right</i></a>
                    <ul class="sub-menu">
                        <li>
                            <a href="#">Commandes en attente</a>
                        </li>
                        <li>
                            <a href="#">Commandes en cours de livraison</a>
                        </li>
                        <li>
                            <a href="#">Commandes en livrées</a>
                        </li>
                    </ul>
                </li>
                @endrole
            </ul>
        </div>
    </div>
    <div class="app-container">
        <div class="search">
            <form>
                <input class="form-control" type="text" placeholder="Type here..." aria-label="Search">
            </form>
            <a href="#" class="toggle-search"><i class="material-icons">close</i></a>
        </div>
        <div class="app-header">
            <nav class="navbar navbar-light navbar-expand-lg">
                <div class="container-fluid">
                    <div class="navbar-nav" id="navbarNav">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link hide-sidebar-toggle-button" href="#"><i class="material-icons">first_page</i></a>
                            </li>
                        </ul>
                    </div>
                    <div class="d-flex">
                        <ul class="navbar-nav">

                            <li class="nav-item">
                                <a class="nav-link toggle-search" href="#"><i class="material-icons">search</i></a>
                            </li>
                            <li class="nav-item hidden-on-mobile">
                                <a class="nav-link" href="{{ route('logout') }}">Se deconnecter</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
        <div class="app-content">
            <div class="content-wrapper">
                <div class="container">
                    <div class="row">
                        <div class="col">
                            <div class="page-description">
                                <h1>Tableau de bord
                                    @role('administrator')
                                    Administrateur
                                    @endrole
                                    @role('fournisseur')
                                    Fournisseur
                                    @endrole
                                </h1>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="card">
                                <div class="card-header">
                                    <h5 class="card-title">Creer article</h5>
                                </div>
                                <div class="card-body">
                                    <div class="example-container">
                                        <div class="example-content">
                                            <form class="row g-3" action="{{route('articles.store')}}" method="POST"  enctype="multipart/form-data">
                                                @csrf
                                                <div class="col-md-6">
                                                    <label for="designation" class="form-label">Designation</label>
                                                    <input type="text" class="form-control" id="designation" name="designation">
                                                </div>
                                                <div class="col-md-6">
                                                    <label for="prix" class="form-label">Prix</label>
                                                    <input type="text" class="form-control" id="prix" name="prix" placeholder="F CFA">
                                                </div>
                                                <div class="col-md-6">
                                                    <label for="description" class="form-label">Description</label>
                                                        <textarea class="form-control" id="description" name="description"  cols="30" rows="10"></textarea>
                                                </div>
                                                <div class="col-md-4">
                                                    <label for="type" class="form-label">Type</label>
                                                    <select id="type" class="form-select" name="type">
                                                        <option selected>Choisir...</option>
                                                        <option>Frites</option>
                                                        <option>Pizza</option>
                                                        <option>Burger</option>
                                                        <option>Steak</option>
                                                    </select>
                                                </div>
                                                <div class="col-12">
                                                    <input type="file" name="photo">
                                                </div>
                                                <div class="col-12">
                                                    <button type="submit" class="btn btn-primary">Creer</button>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Javascripts -->
<script src="/adminAssets/plugins/jquery/jquery-3.5.1.min.js"></script>
<script src="/adminAssets/plugins/bootstrap/js/bootstrap.min.js"></script>
<script src="/adminAssets/plugins/perfectscroll/perfect-scrollbar.min.js"></script>
<script src="/adminAssets/plugins/pace/pace.min.js"></script>
<script src="/adminAssets/plugins/apexcharts/apexcharts.min.js"></script>
<script src="/adminAssets/js/main.min.js"></script>
<script src="/adminAssets/js/custom.js"></script>
<script src="/adminAssets/js/pages/dashboard.js"></script>
</body>
</html>

resources/views/fournisseur/articles/index.blade.php
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Responsive Admin Dashboard Template">
    <meta name="keywords" content="admin,dashboard">
    <meta name="author" content="stacks">

    <!-- Title -->
    <title>Dashboard</title>

    <!-- Styles -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap"
          rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;300;400;500;600;700;800&display=swap"
          rel="stylesheet">
    <link
        href="https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Two+Tone|Material+Icons+Round|Material+Icons+Sharp"
        rel="stylesheet">
    <link href="/adminAssets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/adminAssets/plugins/perfectscroll/perfect-scrollbar.css" rel="stylesheet">
    <link href="/adminAssets/plugins/pace/pace.css" rel="stylesheet">


    <!-- Theme Styles -->
    <link href="/adminAssets/css/main.min.css" rel="stylesheet">
    <link href="/adminAssets/css/custom.css" rel="stylesheet">

    <link rel="icon" type="image/png" sizes="32x32" href="/adminAssets/images/neptune.png"/>
    <link rel="icon" type="image/png" sizes="16x16" href="/adminAssets/images/neptune.png"/>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<div class="app align-content-stretch d-flex flex-wrap">
    <div class="app-sidebar">
        <div class="logo">
            <a href="#" class="logo-icon"><span class="logo-text">Food Market</span></a>
            <div class="sidebar-user-switcher user-activity-online">
                <a href="#">
                    <img src="">
                    <span class="user-info-text">
                            {{auth()->user()->name}}
                        </span>
                </a>
            </div>
        </div>
        <div class="app-menu">
            <ul class="accordion-menu">
                <li class="sidebar-title">
                    Food Market
                </li>
                <li class="active-page">
                    <a href="#" class="active"><i class="material-icons-two-tone">dashboard</i>Dashboard</a>
                </li>
                @role('administrator')
                <li>
                    <a href=""><i class="material-icons-two-tone">star</i>Restaurant<i
                            class="material-icons has-sub-menu">keyboard_arrow_right</i></a>
                    <ul class="sub-menu">
                        <li>
                            <a href="#">Liste</a>
                        </li>
                        <li>
                            <a href="#">Creer</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href=""><i class="material-icons-two-tone">star</i>Utilisateurs<i
                            class="material-icons has-sub-menu">keyboard_arrow_right</i></a>
                    <ul class="sub-menu">
                        <li>
                            <a href="#">Liste</a>
                        </li>
                        <li>
                            <a href="#">Creer</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href=""><i class="material-icons-two-tone">star</i>Fournisseurs<i
                            class="material-icons has-sub-menu">keyboard_arrow_right</i></a>
                    <ul class="sub-menu">
                        <li>
                            <a href="#">Liste</a>
                        </li>
                        <li>
                            <a href="#">Creer</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href=""><i class="material-icons-two-tone">star</i>Commandes<i
                            class="material-icons has-sub-menu">keyboard_arrow_right</i></a>
                    <ul class="sub-menu">
                        <li>
                            <a href="#">Toutes les commandes par fournisseurs</a>
                        </li>
                        <li>
                            <a href="#">Commande validés</a>
                        </li>
                    </ul>
                </li>
                @endrole
                @role('fournisseur')
                <li>
                    <a href=""><i class="material-icons-two-tone">star</i>Articles<i
                            class="material-icons has-sub-menu">keyboard_arrow_right</i></a>
                    <ul class="sub-menu">
                        <li>
                            <a href="#">Liste</a>
                        </li>
                        <li>
                            <a href="#">Creer</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href=""><i class="material-icons-two-tone">star</i>Commandes<i
                            class="material-icons has-sub-menu">keyboard_arrow_right</i></a>
                    <ul class="sub-menu">
                        <li>
                            <a href="#">Commandes en attente</a>
                        </li>
                        <li>
                            <a href="#">Commandes en cours de livraison</a>
                        </li>
                        <li>
                            <a href="#">Commandes en livrées</a>
                        </li>
                    </ul>
                </li>
                @endrole
            </ul>
        </div>
    </div>
    <div class="app-container">
        <div class="search">
            <form>
                <input class="form-control" type="text" placeholder="Type here..." aria-label="Search">
            </form>
            <a href="#" class="toggle-search"><i class="material-icons">close</i></a>
        </div>
        <div class="app-header">
            <nav class="navbar navbar-light navbar-expand-lg">
                <div class="container-fluid">
                    <div class="navbar-nav" id="navbarNav">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link hide-sidebar-toggle-button" href="#"><i class="material-icons">first_page</i></a>
                            </li>
                        </ul>
                    </div>
                    <div class="d-flex">
                        <ul class="navbar-nav">

                            <li class="nav-item">
                                <a class="nav-link toggle-search" href="#"><i class="material-icons">search</i></a>
                            </li>
                            <li class="nav-item hidden-on-mobile">
                                <a class="nav-link" href="{{ route('logout') }}">Se deconnecter</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
        <div class="app-content">
            <div class="content-wrapper">
                <div class="container">
                    <div class="row">
                        <div class="col">
                            <div class="page-description">
                                <h1>Liste des articles
                                </h1>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="card">
                                <div class="card-header">
                                    <h5 class="card-title">Liste des articles</h5>
                                </div>
                                <div class="card-body">
                                    @include('flash-message')
                                    <div class="example-container">
                                        <div class="example-content">
                                            <table class="table">
                                                <thead class="table-dark">
                                                <tr>
                                                    <th scope="col">#</th>
                                                    <th scope="col">Photo</th>
                                                    <th scope="col">Designation</th>
                                                    <th scope="col">Prix</th>
                                                    <th scope="col">Type</th>
                                                    <th scope="col">Actions</th>
                                                </tr>
                                                </thead>
                                                <tbody>
                                                <tr>
                                                    @foreach($articles as $article)
                                                        <th scope="row">{{$article->id}}</th>
                                                        <td>
                                                            <img src="{{$article->photo}}" alt="" width="50" height="50">
                                                        </td>
                                                        <td>{{$article->designation}}</td>
                                                        <td>{{$article->prix}}</td>
                                                        <td>{{$article->type}}</td>
                                                        <td>
                                                            <form method="POST" action="{{route('articles.destroy', $article->id)}}">
                                                                {{ csrf_field() }}
                                                                {{ method_field('DELETE') }}
                                                                <div class="form-group">
                                                                    <input type="submit" class="btn btn-danger" value="Supprimer" onclick="return confirm('Etes-vous sure ?')">
                                                                </div>
                                                            </form>
                                                            <a href="{{route('articles.show', $article->id)}}" class="btn btn-primary">
                                                                Voir
                                                            </a>
                                                            <a href="{{route('articles.edit', $article->id)}}" class="btn btn-secondary">
                                                                Modifier
                                                            </a>

                                                        </td>
                                                    @endforeach
                                                </tr>
                                                </tbody>
                                            </table>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Javascripts -->
<script src="/adminAssets/plugins/jquery/jquery-3.5.1.min.js"></script>
<script src="/adminAssets/plugins/bootstrap/js/bootstrap.min.js"></script>
<script src="/adminAssets/plugins/perfectscroll/perfect-scrollbar.min.js"></script>
<script src="/adminAssets/plugins/pace/pace.min.js"></script>
<script src="/adminAssets/plugins/apexcharts/apexcharts.min.js"></script>
<script src="/adminAssets/js/main.min.js"></script>
<script src="/adminAssets/js/custom.js"></script>
<script src="/adminAssets/js/pages/dashboard.js"></script>
</body>
</html>